server:
  port: 8080

spring:
  application:
    name: rpg-backend

# Game Configuration
game:
  tick-rate: 20
  tile-size: 16
  scale: 4
  max-screen-col: 20
  max-screen-row: 12
  max-map: 10

# CORS
app:
  cors:
    allowed-origins: http://localhost:5173
